spring:
  application:
    name: turbin

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
turbine:
  app-config: order-service,zuul
  cluster-name-expression: new String("default")
  
server:
  port: 5001
